Tests modification.

diff --git a/hw6/Makefile b/hw6/Makefile
--- a/hw6/Makefile
+++ b/hw6/Makefile
@@ -1,5 +1,5 @@
 DEBUG_FLAGS=-DYYDEBUG=1 
-CFLAGS=-std=c++11 -O0 -ggdb $(DEBUG_FLAGS)
+CFLAGS=-std=c++11 #-O0 -ggdb $(DEBUG_FLAGS)
 OUTPUT_DIR=bin
 SRC_DIR=src
 SOURCES=$(SRC_DIR)/ast.h
@@ -8,7 +8,7 @@ LEX_OUT=$(SRC_DIR)/lex.yy.cpp
 BISON_IN=$(SRC_DIR)/LGrammar.g
 BISON_OUT=$(SRC_DIR)/LGrammar.tab.g
 EXEC=$(OUTPUT_DIR)/a.out
-FLEX=flex --debug
+FLEX=flex #--debug
 BISON=bison --defines #--graph
 DOT_FILE=$(OUTPUT_DIR)/LGrammar.dot
 
@@ -36,4 +36,9 @@ clean:
 
 
 test: $(EXEC)
-
+	for f in test/*.L; do \
+		./$(EXEC) "$$f" && diff "$$f".dot "$${f%.L}.dot" >/dev/null; \
+		if [ $$? -ne 0 ]; then \
+			>&2 echo test "$$f" failed!; \
+		fi;\
+	done
