Added word testing and tests.

diff --git a/hw7/Makefile b/hw7/Makefile
--- a/hw7/Makefile
+++ b/hw7/Makefile
@@ -1,17 +1,17 @@
 CXX = g++
-CXXFLAGS = -O2 -Wall -std=c++11
+CXXFLAGS = -O2 -Wall -std=c++14
 LDFLAGS = 
 
-EXE = a.out
+EXEC = a.out
 SRCDIR = src
 BINDIR = bin
 
 OBJECTS = $(patsubst $(SRCDIR)/%.cpp,$(BINDIR)/%.o,$(wildcard $(SRCDIR)/*.cpp))
 
-all: $(EXE)
+all: $(EXEC)
 
-$(EXE): $(BINDIR) $(OBJECTS)
-	$(CXX) $(OBJECTS) -o $(EXE) $(LDFLAGS)
+$(EXEC): $(BINDIR) $(OBJECTS)
+	$(CXX) $(OBJECTS) -o $(EXEC) $(LDFLAGS)
 	
 $(BINDIR)/%.o: $(SRCDIR)/%.cpp
 	$(CXX) $(CXXFLAGS) -c -MMD -o $@ $<
@@ -22,6 +22,28 @@ $(BINDIR):
 	mkdir -p $(BINDIR)
 
 clean:
-	rm -rf $(BINDIR) $(EXE)
+	rm -rf $(BINDIR) $(EXEC)
 
-.PHONY: clean all
+GRAMMAR_EXT=".gr"
+define test_grammar = 
+	for t in $(1)/$(2)/*.txt; \
+	do                        \
+		output="$$t".output;  \
+		rm -f "$$output";     \
+		./$(EXEC) $(1)$(GRAMMAR_EXT) $$t 1>$$output; \
+		if [ $$? -eq $(3) ]; \
+		then \
+			>&2 echo test "$$t" failed!; \
+		fi; \
+	done
+endef
+
+test: $(EXEC)
+	for gr in test/*.gr; do \
+		grname="$${gr%$(GRAMMAR_EXT)}"; \
+		$(call test_grammar,"$$grname","wrong",0); \
+		$(call test_grammar,"$$grname","right",1); \
+	done;
+
+.PHONY: clean all test
+
